{
    "name": "University Management System",
    "version": "19.0.1.1.0",
    "category": "Education",
    "summary": "University ERP - Structure, Academics, Students, Teachers, Enrollments",
    "author": "University Department",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "web",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/cleanup_legacy_models.xml",
        "data/dashboard_data.xml",
        "data/fee_sequence.xml",
        "wizard/enrollment_wizard_views.xml",
        "wizard/student_enrollment_wizard_views.xml",
        "views/faculty_views.xml",
        "views/department_views.xml",
        "views/program_views.xml",
        "views/academic_year_views.xml",
        "views/semester_subject_views.xml",
        "views/classroom_views.xml",
        "views/subject_views.xml",
        "views/class_section_views.xml",
        "views/academic_assignment_views.xml",
        "views/teacher_views.xml",
        "views/student_views.xml",
        # Reports must load before enrollment_views so the server action
        # XML ID exists when the list-header button is resolved.
        "reports/payment_report_template.xml",
        "reports/payment_report.xml",
        "reports/curriculum_report_template.xml",
        "reports/curriculum_report.xml",
        "views/enrollment_views.xml",
        "views/fee_views.xml",
        "views/payment_views.xml",
        "views/dashboard_views.xml",
        "views/school_dashboard_shell_actions.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "school_management/static/src/school_management/dashboard_shell.js",
            "school_management/static/src/school_management/dashboard_shell.xml",
            "school_management/static/src/school_management/dashboard_shell.scss",
            "school_management/static/src/school_management/layout/school_layout.js",
            "school_management/static/src/school_management/layout/school_layout.xml",
            "school_management/static/src/school_management/layout/school_layout.scss",
            "school_management/static/src/school_management/layout/hide_navbar.scss",
            "school_management/static/src/school_management/layout/webclient_patch.js",
            "school_management/static/src/school_management/layout/webclient_patch.xml",
        ],
    },
    "installable": True,
    "application": True,
}