from . import faculty
from . import department
from . import program
from . import academic_year
from . import teacher
from . import classroom
from . import subject
from . import semester_subject
from . import class_section
from . import student
from . import enrollment
from . import fee
from . import payment
from . import dashboard
