from . import faculty
from . import department
from . import program
from . import academic_year
from . import teacher
from . import academic_assignment
from . import res_users
from . import classroom
from . import subject
from . import semester_subject
from . import class_section
from . import student
from . import enrollment
from . import fee
from . import payment
from . import dashboard
from . import res_config_settings
from . import document_signature
from . import capability
from . import lesson_plan
from . import assignment
from . import timetable
from . import notice_board
from . import service_hour
from . import attendance
