from . import test_payment
from . import test_student_signup
from . import test_enrollment
from . import test_integrity
from . import test_security_menus
from . import test_settings
from . import test_document_signature
from . import test_capability
from . import test_user_provisioning
from . import test_grading_integration
from . import test_attendance_sheet
from . import test_department_term
from . import test_record_rules
from . import test_student
from . import test_teacher
