from . import test_payment
from . import test_student_signup
from . import test_enrollment
from . import test_integrity
from . import test_security_menus
from . import test_settings
from . import test_document_signature
from . import test_capability
from . import test_user_provisioning
