from . import common
from . import test_payment
from . import test_student_signup
from . import test_enrollment
from . import test_integrity
from . import test_security_menus
from . import test_settings
from . import test_document_signature
from . import test_capability
from . import test_user_provisioning
from . import test_grading_integration
from . import test_attendance_sheet
from . import test_department_term
from . import test_record_rules
from . import test_student
from . import test_teacher
from . import test_teacher_managed_scopes
from . import test_semester_subject
from . import test_staff_attendance
from . import test_role_dashboard_access
from . import test_transcript_request
from . import test_timetable_attendance_flow
from . import test_timetable_generation
from . import test_study_plan
